
<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r}
# run scripts for necessary packages and objects as necessary
if (!"chHexs"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("settings--profile.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
if (!"calc_cps_transitions" %in% objects()) source_rmd("method--nowcasting-functions.Rmd", echo = FALSE)
```

```{r load final results from now-casting and select a sensitivity}
load(file = glue("{output_path}Eligibility estimates using conditional transition ratio - {my_output_tag}.Rda"))
load(file = glue("{output_path}pop_data_{my_output_tag}.Rda"))
load(file = glue("{output_path}geo_data_{my_output_tag}.Rda"))
load(file = glue("{output_path}acs5_data_{my_output_tag}.Rda"))
```

```{r select a sensitivity}
# /*\ This is something that users of this method must specify
# Below, there are several `if` clauses that already implement--and describe--
# logic for selecting a sensitivity specific for each of several run specifications

if (str_detect(my_output_tag, "IL2022")) {
  # Rationale is we're not just focused on metro areas, and we want the most
  # up-to-date estimates as possible
  nowcast_selected_sens <-
    nowcast_out[cps_geo_subsample == "none" & 
                cps_base_recency  == "most_recent"]
} else if (str_detect(my_output_tag, "Cook|Chi")) {
  # Rationale is we are focused on a metro areas, and we want estimates for 2022
  # that are parallel to 2021, given that this method is part of a sequence of
  # a sequence of annual reports
  nowcast_selected_sens <-
    nowcast_out[cps_geo_subsample == "metros" & 
                cps_base_recency  == "allbase"]
} else if (str_detect(my_output_tag, "Dirigo")) {
  nowcast_selected_sens <-
    nowcast_out[cps_geo_subsample == "none" & 
                cps_base_recency  == "most_recent"]
}
```


```{r generate parallel constructions for base (sae) and nowcast}
# Establish a general setup of parallel field names

nowcast_parallel_setup <- 
  nowcast_selected_sens %>%
  # /!\ Need to produce/bring in standard errors for the SAE. Assigning these 0
  # as a placeholder.
  mutate(base_share_se = 0,
         nowcast_share = elig_share,
         nowcast_share_se = elig_share_se)

# For each output, select the sensitivity and (calculation of) related measure
# /!\ These related `base_share` measures are, in many cases, not aligned with
# the estimated measures themselves (and so we set them as NA).
# This is because the only `share_#_#` predictors that are carried along are 
# those that were predicted in the SAE estimation. The most direct updated
# step would be to produce different runs of the SAE, although this is currently
# highly time-consuming.

nowcast_parallel_incpov_le50 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le50_post_adj",
         str_detect(sae_spec, "incpov_ctrls_mix")) %>% 
  mutate(base_share = share_0_50)

nowcast_parallel_incpov_le100 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le100_post_adj",
         str_detect(sae_spec, "incpov_ctrls_100")) %>% 
  mutate(base_share = share_0_100)

nowcast_parallel_incpov_le185 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le185_post_adj",
         str_detect(sae_spec, "incpov_ctrls_100")) %>% 
  mutate(base_share = NA)

nowcast_parallel_incpov_le200 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le200_post_adj",
         str_detect(sae_spec, "incpov_ctrls_100")) %>% 
  mutate(base_share = share_0_100 + share_100_200)

nowcast_parallel_incpov_le225 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le225_post_adj",
         str_detect(sae_spec, "incpov_ctrls_100")) %>% 
  mutate(base_share = NA)

nowcast_parallel_incpov_le400 <- 
  nowcast_parallel_setup %>% 
  filter(outcome_var == "incpov_le400_post_adj",
         str_detect(sae_spec, "incpov_ctrls_100")) %>% 
  mutate(base_share = share_0_100 + share_100_200 + share_200_300 + share_300_400)

bind_list <- 
  list(nowcast_parallel_incpov_le50,
       nowcast_parallel_incpov_le100,
       nowcast_parallel_incpov_le185,
       nowcast_parallel_incpov_le200,
       nowcast_parallel_incpov_le225,
       nowcast_parallel_incpov_le400)

```

```{r add all relevant ccdf sensitivities}

for (ccdf_spec in unique(str_subset(nowcast_parallel_setup$outcome_var, "ccdf_elig_incratio"))) {
  sensitivity_to_add <- 
    nowcast_parallel_setup %>% 
    filter(outcome_var == ccdf_spec,
           str_detect(sae_spec, "ccdf_wk_pov")) %>% 
    mutate(base_share = NA)
  
  bind_list <- append(bind_list, list(sensitivity_to_add))
}

```



```{r combined the parallel constructions for base (sae) and nowcast}

# Generate parallel base/nowcast constructions wide by base/now measures 
nowcast_parallel_preshape <- 
  bind_rows(bind_list) %>% 
  dplyr::select(GEOID, outcome_var, age, base_share, base_share_se, nowcast_share, nowcast_share_se) %>% 
  # /!\ ** This unique() should not be necessary. However, it's occurring because
  # there are duplicates resulting from a merge of the crosswalk file, due to
  # overlaps with ZCTAs. There should be a cleaner, unique crosswalk of census
  # shapes--tract, PUMA, and County--with other crosswalks occurring later, as needed.
  unique()

# Reshape to long format, with only different stats wide
nowcast_parallel <- 
  nowcast_parallel_preshape %>% 
  pivot_longer(cols = matches("share")) %>% 
  separate(col = name, 
           into = c("pd", "stat"),
           sep = "_",
           extra = "merge") %>% 
  pivot_wider(names_from = stat,
              values_from = value)
```

```{r merge population stats to calculate counts}
pop_by_age_long <- 
  pop_by_age %>% 
  pivot_longer(cols = matches("age_.+_count")) %>% 
  mutate(age = str_replace(name, "_count", ""),
         pd = case_when(year == base_year     ~ "base",
                        year == base_year + 1 ~ "nowcast")) %>% 
  rename(pop_count = value,
         GEOID = GEOID_TR20) %>%
  # /!\ Here again is where we need to bring in a proper standard error for
  # population count estimates
  mutate(pop_count_se = 0) %>% 
  dplyr::select(-name)

nowcast_parallel_counts <- 
  nowcast_parallel %>% 
  merge(pop_by_age_long,
        by = c("GEOID", "age", "pd"),
        all.x = TRUE) %>% 
  data.table() %>%
  mutate(count    = share*pop_count,
         count_se = se_product(share, pop_count, share_se, pop_count_se))
```

```{r save results}
save(nowcast_parallel_counts,
     most_recent_months,
     file = glue("{output_path}Now-cast counts at the tract level, pre-disaggregation - {my_output_tag}.Rda"))
```

```{r reshape measures long}
share_pre_post <- 
  nowcast_parallel_counts %>% 
  dplyr::select(-year) %>% 
  pivot_longer(cols = matches("share|count")) %>% 
  unite(wide_name, name, pd, sep = "_") %>% 
  pivot_wider(names_from = wide_name,
              values_from = value)
```

### Map Now-cast Estimates

```{r generate maps for now-cast estimates, fig.height = 12}
tractShp %>% 
  merge(share_pre_post, 
        by = "GEOID") %>%
  filter(outcome_var %like% "le50") %>%
  ggplot(aes(fill = share_nowcast)) +
  geom_sf(color = NA) +
  facet_wrap(~ outcome_var) +
  theme_void() +
  theme(strip.text = element_text(size = 14))

```



### Examine Now-cast Estimates versus Base-Year (SAE) Estimates

We compare now-cast estimates to baseline SAE estimates for only Head Start eligibility, because in the SAE estimates we do not currently estimate <50% as its own threshold, nor income measures directly connected to CCDF eligibility.

```{r function to compare now-cast vs SAE}
comp_nowcast_vs_sae <- function(share_ests, title, xlab, ylab, save_tag) {
  
  my_plot <- 
    ggplot(share_ests,
           aes(x = share_base,
               y = share_nowcast)) +
    geom_point(alpha = 0.2) +
    geom_45(color = "red") +
    geom_smooth(se = FALSE,
                color = "blue") +
    # facet_wrap(~ sae_spec) +
    scale_x_continuous(labels = percent) +
    scale_y_continuous(labels = percent) +
    labs(title = title,
         x = xlab,
         y = ylab) +
    theme_minimal() +
    theme(legend.position = "bottom",
          axis.text = element_text(size = 11))
  
  if (save_tag != "") {
    ggsave(plot = my_plot,
           filename = glue("{output_path}nowcast_vs_sae_{my_output_tag}_{save_tag}.png"))
  }
  
  return(my_plot)
}
```

```{r compare now-cast vs SAE for deep poverty}
comp_nowcast_vs_sae(share_ests = share_pre_post %>% filter(str_detect(outcome_var, "incpov_le50")),
                    title = case_when(my_output_tag == "IL" ~ "Tract-Level Now-Cast Estimates are Generally Above Baseline",
                                      TRUE ~ ""),
                    xlab = glue("Baseline (SAE) - {base_year}"),
                    ylab = glue("Now-Cast - {base_year+1}"),
                    save_tag = "incpov_le50")
```

```{r compare now-cast vs SAE for HS}
comp_nowcast_vs_sae(share_ests = share_pre_post %>% filter(str_detect(outcome_var, "incpov_le100")),
                    title = case_when(my_output_tag == "IL" ~ "Tract-Level Now-Cast Estimates are Generally Above Baseline",
                                      TRUE ~ ""),
                    xlab = glue("Baseline (SAE) - {base_year}"),
                    ylab = glue("Now-Cast - {base_year+1}"),
                    save_tag = "incpov_le100")
```

```{r compare now-cast vs SAE for CCAP}
comp_nowcast_vs_sae(share_ests = share_pre_post %>% filter(str_detect(outcome_var, glue("{local_ccdf_incratio_base}$"))),
                    title = case_when(my_output_tag == "IL" ~ "Tract-Level Now-Cast Estimates are Generally Above Baseline",
                                      TRUE ~ ""),
                    xlab = glue("Baseline (SAE) - {base_year}"),
                    ylab = glue("Now-Cast - {base_year+1}"),
                    save_tag = "ccdf_elig")
```


```{r add community characteristics}
share_pre_post_chars <- 
  left_join(share_pre_post, 
            acs5tract,
            by = "GEOID")
```

```{r function to plot diffs vs community characteristics}
plot_elig_diff_vs_char <- 
  function(outcome_string,
           outcome_desc,
           char_field,
           char_desc,
           save_tag = "") {
    
    dt_plot <-
      share_pre_post_chars %>% 
      filter(str_detect(outcome_var, outcome_string))
    
    my_plot <- 
      ggplot(dt_plot,
             aes(x = get(char_field), # ed_lths
                 y = share_nowcast - share_base)) +
      geom_point(alpha = 0.2) +
      geom_hline(yintercept = 0,
                 color = "darkblue",
                 linewidth = 0.75) +
      geom_smooth(color = "red",
                  se = FALSE) +
      scale_x_continuous(label = percent) +
      scale_y_continuous(label = percent) +
      labs(x = char_desc,
           y = glue("Change in {outcome_desc} - {base_year} to {base_year + 1}")) +
      theme_minimal()
    
    if (save_tag != "") {
      ggsave(plot = my_plot,
             filename = glue("{output_path}Difference in Eligibility in {outcome_desc} {save_tag}_{my_output_tag}.png"),
             width = 6,
             height = 4,
             units = "in")
    }
    print(my_plot)
  }
```


```{r}
plot_elig_diff_vs_char(outcome_string = "incpov_le100",
                       outcome_desc   = "HS Eligibility", 
                       char_field     = "raceeth_wh_nonh_est",
                       char_desc      = "% White Non-Hisp in Tract",
                       save_tag       = "by white residence")
```

```{r}
plot_elig_diff_vs_char(outcome_string = glue("ccdf_elig_incratio_{local_ccdf_incratio_base}"),
                       outcome_desc   = glue("{local_ccdf_name_short} Eligibility"), 
                       char_field     = "raceeth_wh_nonh_est",
                       char_desc      = "% White Non-Hisp in Tract",
                       save_tag       = "by white residence")
```

