
<!-- This .Rmd file is set up to run either independently by checking for 
the presence of necessary objects in the global environment and running 
related scripts if not, or also as a child to the "main-doc". For that latter
reason, comments and headings that are not relevant to a final report to
pubic audiences are suppressed or moved to code chunks that can optionally be 
`echo`ed as desired. -->

```{r}
# set flags for running this script
print_documentation <- FALSE
```

```{r}
# run scripts for necessary packages and objects as necessary
if (!"chHexs"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("settings--profile.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)

load(glue("{output_path}geo_data_{my_output_tag}.Rda"))

source("method--pull-and-process-acs5.R")

```

```{r run acs5 data pull if data is not available}
acs5_filename <- glue("{output_path}acs5_variables_{my_output_tag}.csv")
if (!file.exists(acs5_filename)) {
  source("pull--acs5-general-data.R")
}
```


## Details of ACS 5-Year Aggregate Data Development

```{r read ACS 5-year data and add miscellaneous constructions not handled in the pull}
acs5tract <- 
  fread(acs5_filename) %>% 
  # Keep tracts with non-zero population.
  .[(endyear == max(endyear)) & (tot_families_count > 0)] %>%
  mutate(raceeth_wh_est   = raceeth_wh_h_est + raceeth_wh_nonh_est,
         raceeth_wh_se    = sqrt(raceeth_wh_h_se^2 + raceeth_wh_nonh_se^2),
         raceeth_wh_se    = se_col_sum(raceeth_wh_h_se, raceeth_wh_nonh_se),
         raceeth_wh_count = raceeth_wh_h_count + raceeth_wh_nonh_count,
         
         raceeth_bl_est   = raceeth_bl_h_est + raceeth_bl_nonh_est,
         raceeth_bl_se    = se_col_sum(raceeth_bl_h_se, raceeth_bl_nonh_se),
         raceeth_bl_count = raceeth_bl_h_count + raceeth_bl_nonh_count,
         
         raceeth_h_est    = raceeth_amind_h_est + raceeth_as_h_est + raceeth_bl_h_est + 
           raceeth_mult_h_est + raceeth_oth_h_est + raceeth_pacisl_h_est + raceeth_wh_h_est,
         raceeth_h_se     = se_col_sum(raceeth_amind_h_se, raceeth_as_h_se, 
                                       raceeth_bl_h_se, raceeth_mult_h_se, raceeth_oth_h_se,
                                       raceeth_pacisl_h_se, raceeth_wh_h_se),
         raceeth_h_count = raceeth_amind_h_count + raceeth_as_h_count + raceeth_bl_h_count + 
           raceeth_mult_h_count + raceeth_oth_h_count + raceeth_pacisl_h_count +
           raceeth_wh_h_count,
         
         ed_lths_n     = m_lesshs_est  * m_lesshs_count   + f_lesshs_est  * f_lesshs_count,
         ed_hs_n       = m_hsgrad_est  * m_hsgrad_count   + f_hsgrad_est  * f_hsgrad_count,
         ed_somecoll_n = m_somecoll_est* m_somecoll_count + f_somecoll_est* f_somecoll_count,
         ed_coll_n     = m_coll_est    * m_coll_count     + f_coll_est    * f_coll_count,
         ed_lths     = ed_lths_n     / (m_lesshs_count   + f_lesshs_count),
         ed_hs       = ed_hs_n       / (m_hsgrad_count   + f_hsgrad_count),
         ed_somecoll = ed_somecoll_n / (m_somecoll_count + f_somecoll_count),
         ed_coll     = ed_coll_n     / (m_coll_count     + f_coll_count)) %>% 
  data.table()

```


```{r prepare ACS 5-year geographic identifiers - tract-level}
acs5tract <- 
  acs5tract %>%
  .[j = geo_val_string := str_pad(geo_val, width = 11, side = "left", pad = 0)] %>%
  .[j = `:=`(STATEFIP  = substr(geo_val_string, 1, 2),
             COUNTYFIP = substr(geo_val_string, 3, 5),
             TRACTFIP  = substr(geo_val_string, 6, 11),
             YEAR = endyear)] %>%
  rename(GEOID = geo_val_string) %>% 
  select(-one_of("source", "endyear", "geo", "geo_val", "NAME")) %>%
  # Set order of the rows
  setorder(YEAR, STATEFIP, COUNTYFIP, TRACTFIP) %>%
  # Set order of the columns
  setcolorder(c("YEAR", "STATEFIP", "COUNTYFIP", "TRACTFIP"))
```

<!-- ### Aggregate ACS 5-Year Data to the PUMA level -->

<!-- Tract-level ACS5 data are aggregated to the PUMA-level for use in certain sensitivities of the Small Area Estimation method which develop estimates at the PUMA level (although our end goal is to get to smaller geographic levels.) -->

```{r prepare ACS 5-year geographic identifiers - PUMA-level}
# Add PUMA identifiers to tract-level 5-year aggregate data set. Drop tract identifiers.
acs5puma <- 
  merge(acs5tract, 
        geo_crosswalk, 
        by = c("STATEFIP", "COUNTYFIP", "TRACTFIP", "GEOID"), 
        all.x = TRUE) %>%
  filter(!is.na(PUMA)) %>%
  select(-COUNTYFIP, -TRACTFIP) %>%
  setorder(YEAR, STATEFIP, PUMA) %>%
  setcolorder(c("YEAR", "STATEFIP", "PUMA"))
```

<!-- For tract-level average/share variables, store "stubs" of variable names in a list. -->

<!-- Multiply tract-level average/share variables by corresponding tract-level denominator count variables to produce tract-level numerator count variables. -->

<!-- Recall that original _count variables from the ACS input files store tract-level denominator count variables.
/!\ This is an aspects of naming conventions that is confusing and is worth reconsidering for clarity in on-going work -->

```{r prepare ACS 5-year geographic identifiers}

avg_list <- str_subset(cn(acs5puma), "_est$") %>% str_remove(., "_est")

check <- copy(acs5puma)

# Go through all variables and adjust them to be suitable for summing where:
# * "_est" is converted to a numerator count, 
# * "_se" is converted to a variance
# * "_count" is left as is. That's the denominator.
for (var_name in avg_list) {
  # /!\ Kludge to ignore fields that don't match conventions
  if (str_detect(var_name, "Male_noSp|Female_noSp|^Married|pctMarried|^famtype")) next
  acs5puma <- 
    acs5puma %>% 
    .[, paste0(var_name, "_est") := eval(parse(text=paste0(var_name, "_est")))*eval(parse(text=paste0(var_name, "_count")))] %>%
    .[, paste0(var_name, "_se")  := eval(parse(text=paste0(var_name, "_se")))^2]
}

if (FALSE) {
  acs5puma[PUMA == 3401, str_subset(cn(acs5puma), "r0to50"), with = FALSE]
  check[j = numer := incpov_r0to50_est*incpov_r0to50_count]
  check[PUMA== 3401, .(numer)]  
}

# Perform the sum
acs5puma <-
  acs5puma %>%
  .[, lapply(.SD, sumNA), 
    by = .(YEAR, STATEFIP, PUMA),
    .SDcols = str_subset(cn(acs5puma), "_est$|_count$|_se$")]

if (FALSE) {
  acs5puma[PUMA == 3401, str_subset(cn(acs5puma), "r0to50"), with = FALSE]
  check[PUMA == 3401, .(sum(numer), sum(incpov_r0to50_count))]  
}

# Construct PUMA-level average/share variables by taking the ratio of the PUMA-level numerator count variable and the PUMA-level denominator count variable.
# Construct PUMA-level standard errors by taking the square root of the PUMA-level variance.

for (var_name in avg_list) {
  # /!\ Kludge to ignore fields that don't match conventions
  if (str_detect(var_name, "Male_noSp|Female_noSp|^Married|pctMarried|^famtype")) next
  acs5puma <-
    acs5puma %>%
    # /!\ Could improve readability with glue(), and ep <- function(x) eval(parse(text = x))
    .[, paste0(var_name, "_est") := eval(parse(text=paste0(var_name, "_est")))/eval(parse(text=paste0(var_name, "_count")))] 
}

if (FALSE) {
  acs5puma[PUMA == 3401, str_subset(cn(acs5puma), "r0to50"), with = FALSE]
  check[PUMA == 3401, sum(numer) / sum(incpov_r0to50_count)]  
}

se_list <- str_subset(cn(acs5puma), "_se$") %>% str_remove(., "_se")
for (var_name in se_list) {
  # /!\ Kludge to ignore fields that don't match conventions
  if (str_detect(var_name, "Male_noSp|Female_noSp|^Married|pctMarried|^famtype")) next
  acs5puma <-
    acs5puma %>%
    .[, paste0(var_name, "_se") := sqrt(eval(parse(text=paste0(var_name, "_se"))))]
}

```

```{r compare the tract- and puma-level data, eval = developer_mode}
acs5comp <- 
  acs5tract %>% 
  merge(geo_crosswalk %>% select(GEOID, PUMA),
        by = "GEOID") %>% 
  merge(acs5puma,
        by = "PUMA")

# Looks right
ggplot(acs5comp, aes(incpov_r0to50_est.y, incpov_r0to50_est.x)) + 
  geom_point(alpha = 0.2) +
  geom_smooth()

# Audit the construction of the acs5puma
acs5tract_test <- 
  acs5tract %>% 
  merge(geo_crosswalk %>% select(GEOID, PUMA),
        by = "GEOID") %>% 
  mutate(incpov_r0to50_num = incpov_r0to50_est*incpov_r0to50_count) %>% 
  group_by(PUMA) %>% 
  summarize(wgt = sum(incpov_r0to50_count),
            n   = sum(incpov_r0to50_num)) %>% 
  mutate(r   = n / wgt) %>% 
  merge(acs5puma %>% select(PUMA, incpov_r0to50_est, incpov_r0to50_count),
        by = "PUMA")
#View(acs5tract_test %>% select(wgt, n, r, incpov_r0to50_est, incpov_r0to50_est))
```

```{r}
save(acs5tract, acs5puma,
     file = glue("{output_path}acs5_data_{my_output_tag}.Rda"))
```

```{r prepare county argument for fresh pull of acs5 data}
if (exists("my_county_fip")) county_val <- my_county_fip else county_val <- NULL
```

```{r fresh pull of both income and work status tables}
# "Age by Ratio of Income to Poverty Level In the Past 12 Months"
acs5_incpov_byage_raw    <- pull_table("B17024", state = my_state_abbr, county = county_val, year = acs5_year)

# "Relationship To Householder For Children Under 18 Years In Households"
acs5_famconfig_wKids_raw <- pull_table("B23007", state = my_state_abbr, county = county_val, year = acs5_year)

```

```{r determine closest fpl cutoff to ccdf eligibility threshold}
ccdf_inc_thresh_fpl <- get_fpl_thresh_for_ccdf()

# Determine which inc-to-pov value from the tables is closest to the ccdf fpl
# cutoff
acs5_income_cutpoints <- c(0, 50, 75, 100, 125, 150, 175, 185, 200, 300, 400, 500)
dev <- 
  (acs5_income_cutpoints - ccdf_inc_thresh_fpl) %>% 
  abs()

nearest_incpov_cutpoint_to_ccdf <- 
  acs5_income_cutpoints[which(dev == min(dev))]
```

```{r functions to recode acs5 inc-to-pov fields into a custom partition}
# Determine partitions for constructing one implementation
# - make a df with these values, mapped to lower values, for a given value, return
#    those with left-value
dfIncPovCutoffs <- 
  data.frame(incpov = unique(acs5_incpov_byage_raw$inc_to_pov_ratio)) %>% 
  filter(incpov != "All") %>% 
  mutate(left = 
           incpov %>% 
           str_replace("IncPov(\\d+)(to|plus).*", "\\1") %>% 
           as.numeric())

return_incpov_fields_bounds <- function(low, high) {
  out <- filter(dfIncPovCutoffs, left >= low)
  if (!is.na(high)) {
    out <- filter(out, left < high)
  }
  return(out$incpov)
}
if (FALSE) {
  return_incpov_fields_bounds(0, 100)
  return_incpov_fields_bounds(0, 101)
  return_incpov_fields_bounds(500, NA)
}

recode_incpov_fields_vec <- function(vec) {
  # Initialize output
  out <- 
    dfIncPovCutoffs %>% 
    mutate(recoding = incpov)
  
  # Go through out cutpoint to create mapping
  for (v in 1:length(vec)) {
    low <- vec[v]
    high <- vec[v+1]
    corresponding_fields <- return_incpov_fields_bounds(low, high)
    if (is.na(high)) {
      recode_val <- glue("IncPov{low}plus")
    } else {
      recode_val <- glue("IncPov{low}to{high}")
    }
    out <- 
      out %>% 
      mutate(recoding = ifelse(incpov %in% corresponding_fields,
                             recode_val,
                             recoding))
  }
  return(out)
}

if (FALSE) {
  recode_incpov_fields_vec(c(0, 50, 100, 200, 500))
}
```

```{r generate recoding schemes for income-to-poverty aggregation}
inspect_fields(acs5_incpov_byage_raw)

recode_incpov <- function(recoding_cuts) {
  recoding_scheme <- recode_incpov_fields_vec(recoding_cuts)
  acs5_incpov_byage_raw %>% 
  filter(inc_to_pov_ratio != "All") %>% 
  mutate(inc_to_pov_recode = recoding_scheme$recoding[match(inc_to_pov_ratio, recoding_scheme$incpov)])
}

incpov_for100s_recoded <- recode_incpov(c(0, 100, 200, 300, 400))
incpov_forMix_recoded  <- recode_incpov(c(0,  50, 100, 200, 400))
incpov_forCcdf_recoded <- recode_incpov(c(0, 100, nearest_incpov_cutpoint_to_ccdf, 500))

# Check completeness of recoding
stopifnot(!any("NEEDS RECODING" %in% 
                 c(incpov_for100s_recoded$inc_to_pov_recode, 
                    incpov_forMix_recoded$inc_to_pov_recode)))
if (FALSE) {
  incpov_for100s_recoded %>% select(inc_to_pov_ratio, inc_to_pov_recode) %>% unique()
  incpov_forMix_recoded  %>% select(inc_to_pov_ratio, inc_to_pov_recode) %>% unique()
  incpov_forCcdf_recoded %>% select(inc_to_pov_ratio, inc_to_pov_recode) %>% unique()
}
```

```{r execute aggregations of income-to-poverty data}
agg_incpov_recoding <- function(acs5_incpov_recoded) {
  acs5_incpov_recoded %>% 
    select(-inc_to_pov_ratio) %>% 
    construct_fields(
      numerator = "inc_to_pov_recode",
      by_vars = "age",
      subset_cond = "age %in% c('Age0to6', 'Age6to11')",
      subset_descr = "")
}

incpov_for100s <- agg_incpov_recoding(incpov_for100s_recoded)
incpov_forMix  <- agg_incpov_recoding(incpov_forMix_recoded)
incpov_forCcdf <- agg_incpov_recoding(incpov_forCcdf_recoded)

# Check on the completeness of the output
if (FALSE) {
  sub_cn(incpov_for100s, "^rInc.+Age0") %>% sort_by_char_nums() %>% levels()
  sub_cn(incpov_forMix,  "^rInc.+Age0") %>% sort_by_char_nums() %>% levels()
  sub_cn(incpov_forCcdf, "^rInc.+Age0") %>% sort_by_char_nums() %>% levels()
}
```

```{r construct desired work eligibility field}
inspect_fields(acs5_famconfig_wKids_raw)

workelig_withKids <- 
  construct_fields(
    df = acs5_famconfig_wKids_raw,
    subset_cond = "own_kids_under18 == 'SomeKidsUnder18'",
    #denom_subset = "status == 'All'",
    numerator = "status", 
    numerator_vals = c("HusbandEmplWifeEmpl", "Empl"),
    numerator_lab  = c("WorkEligFam"),
    subset_descr = "")
```


```{r merge together data sets intended for estimating ccdf eligibility}
merge_by_geoid <- function(x, y) {
  # Remove duplicate fields
  non_dup_fields <- c(cn(y)[!cn(y) %in% cn(x)], "GEOID")
  merge(x, y %>% select(one_of(non_dup_fields)), by = "GEOID", all = TRUE)
}
acs5_ccdf <-
  Reduce(merge_by_geoid,
         list(incpov_for100s, incpov_forMix, incpov_forCcdf, workelig_withKids))

save(acs5_ccdf,
     file = glue("{output_path}acs5_ccdf_{my_output_tag}.Rda"))
```


