
```{r}
# run scripts for necessary packages and objects as necessary
if (!"meanNA"        %in% objects()) source("settings--main.R", echo = FALSE)
if (!"my_state_abbr" %in% objects()) source("method--read-customization-file.R", echo = FALSE)
if (!"bin_age"       %in% objects()) source("method--general-helper-functions.R", echo = FALSE)
```

```{r load final aggregates}
# Load final aggregated output
load(file = glue("{output_path}Final ELPEP Estimates in Multiple Geographic Aggregates - {my_output_tag}.Rda"))

# Load other related content for reference
load(glue("{output_path}Now-cast counts at the tract level, pre-disaggregation - {my_output_tag}.Rda"))

```

#### Generate Excel Tables with Estimates at Each Geographic Aggregation for CCDF

```{r develop time period indication for output }
# Automate the calculation of the time period
# /!\ This currently assumes that "most_recent" is the chosen sensitivity from 
# 03a. Need to find a way to pass the actual choice from 03a to here. This is not
# complicated, but just needs light planning.

most_recent_range <- 
  most_recent_months %>% 
  sort() %>% 
  paste0("-01") %>% 
  as.Date()
date1 <- most_recent_range[1]
date2 <- most_recent_range %>% .[length(.)]
if (year(date1) == year(date2)) {
  date_range <- paste0(format(date1, "%b"), "-",
                       format(date2, "%b %Y"))
} else {
  date_range <- paste0(format(date1, "%b %Y"), "-",
                       format(date2, "%b %Y"))
}
```

```{r identify label for income measure used for thresholds}
ccdf_income_thresh_label <- 
    ifelse(exists("local_custom_thresh_label"),
           local_custom_thresh_label,
           "FPL")
```


```{r function to output excel sheets for various levels of geographic aggregation}
write_agg_output <- function(outcomes_regex, age_regex = ".+", agg_levels, out_label) {

  if (exists("excel_front_page_file")) {
    #addWorksheet(wb, "Front page")
    wb <- openxlsx::loadWorkbook(excel_front_page_file)
    # openxlsx::write.xlsx(xlsxFront,
    #                      wb,
    #                      sheetName = "Front Page")
  } else {
    wb <- openxlsx::createWorkbook()
  }
  
  for (lvl in agg_levels) {
    add_sheet <-
      copy(lvl[["agg_table"]]) %>% 
      arrange(get(lvl[["agg_field"]])) %>% 
      setnames(lvl[["agg_field"]], lvl[["sheet_name"]]) %>% 
      filter(pd == "nowcast",
             cps_base_recency == "most_recent",
             str_detect(outcome_var, outcomes_regex)) %>% 
      select(-cps_base_recency) %>% 
      rename(Age = age) %>% 
      # convert age to narrative
      mutate(
        Outcome = 
          case_when(str_detect(outcome_var, "^ccdf") ~ 
                      str_replace(outcome_var, 
                                  "ccdf_elig_incratio_(\\d+)",
                                  glue("{local_ccdf_name_short} - \\1% {ccdf_income_thresh_label}")),
                    str_detect(outcome_var, "_le50_")  ~ "Below 50% FPL",
                    str_detect(outcome_var, "_le100_") ~ "Below 100% FPL",
                    str_detect(outcome_var, "_le185_") ~ "Below 185% FPL",
                    str_detect(outcome_var, "_le200_") ~ "Below 200% FPL",
                    str_detect(outcome_var, "_le225_") ~ "Below 225% FPL",
                    str_detect(outcome_var, "_le400_") ~ "Below 400% FPL"),
        
        Outcome = sort_by_char_nums(Outcome),
        
        # Calculate bounds, and round
        count_lb = round(count + qnorm(.1)*count_se),
        count_ub = round(count + qnorm(.9)*count_se),
        count    = round(count),
        pop_count = round(pop_count), # This is in order to get "round" values of share
        
        # (Re)calculate share to be consistent with the rounded counts.
        # This is most significant for small geographies, where counts may
        # be small--and thus likely a familiar percentage, or even 0
        share = (count / pop_count) %>% replace_na(0),
        share_se = se_proportion(count, pop_count, count_se, pop_count_se),
        share_lb = pmax(share + qnorm(.1)*share_se, 0) %>% replace_na(0),
        share_ub = pmin(share + qnorm(.9)*share_se, 1) %>% replace_na(0)) %>% 
      dplyr::select(-count_se, -share_se, -pop_count_se) %>% 
      pivot_longer(cols = matches("(count|share)(_|$)")) %>% 
      mutate(stat = case_when(name == "pop_count" ~ "Overall #",
                              name %like% "count" ~ "#",
                              name %like% "share" ~ "%"),
             calc = case_when(name %like% "_lb" ~ ", lower bound",
                              name %like% "_ub" ~ ", upper bound",
                              TRUE ~ ""),
             Outcome = case_when(name == "pop_count" ~ "",
                                 TRUE                ~ paste0(" ", Outcome)),
             
             label = glue("{Age}{Outcome}, {date_range} -- {stat}{calc}")) %>% 
      arrange(Age, Outcome) %>% 
      dplyr::select(-pd, -outcome_var, -Age, -Outcome, -name, -stat, -calc) %>% 
      # Use a unique() to compress the overall population rows across outcomes
      unique() %>% 
      pivot_wider(names_from = label,
                  values_from = value)
    
    openxlsx::addWorksheet(wb, 
                           sheetName = lvl[["sheet_name"]])
    
    # Write the data to the new sheet
    openxlsx::writeDataTable(wb, 
                   sheet = lvl[["sheet_name"]], 
                   x = add_sheet,
                   colNames = TRUE, 
                   rowNames = FALSE,
                   tableStyle = "TableStyleMedium2")
    
    # Format specified columns as percentage
    openxlsx::addStyle(wb, 
             sheet = lvl[["sheet_name"]], 
             style = openxlsx::createStyle(numFmt = "0.0%"), 
             cols = str_which(cn(add_sheet), "-- %"),
             rows = 1:nrow(add_sheet)+1,
             gridExpand = TRUE)
    
    # Format specified columns as comma
    openxlsx::addStyle(wb, 
             sheet = lvl[["sheet_name"]], 
             style = openxlsx::createStyle(numFmt = "#,##0"), 
             cols = str_which(cn(add_sheet), "#$"),
             rows = 1:nrow(add_sheet)+1,
             gridExpand = TRUE)
    
    # Wrap text for header row
    openxlsx::addStyle(wb, 
             sheet = lvl[["sheet_name"]], 
             style = openxlsx::createStyle(wrapText = TRUE), 
             cols = 1:ncol(add_sheet),
             rows = 1,
             gridExpand = TRUE)
    
    # Freeze the top row and leftmost column
    openxlsx::freezePane(wb,
               sheet = lvl[["sheet_name"]],
               firstRow = TRUE,
               firstCol = TRUE)
    
    # Set column widths
    openxlsx::setColWidths(wb, 
                 sheet = lvl[["sheet_name"]], 
                 cols = 2:ncol(add_sheet), 
                 widths = 18)
    
    # Group and hide columns corresponding to upper and lower bounds
    openxlsx::groupColumns(wb,
                 sheet = lvl[["sheet_name"]],
                 cols = str_which(cn(add_sheet), "bound$"),
                 hidden = TRUE)
  }
  
  openxlsx::saveWorkbook(
    wb, 
    file = glue("{output_path}{out_label} eligibility estimates by geography - {my_output_tag}.xlsx"),
    overwrite = TRUE
  )
}
```


```{r write various levels of geographic aggregation out to file for ccdf}

output_fpl_cuts_regex <- 
  output_fpl_cuts %>%
  str_split(pattern = ",") %>% 
  unlist() %>% 
  str_trim() %>% 
  paste(collapse = "|")

outcomes_out_regex <- glue("ccdf_elig_incratio_|incpov_le({output_fpl_cuts_regex})")

lAgg_for_output <- 
  list(list(agg_table = nowcast_agg_tract,
            agg_field = "GEOID",
            sheet_name = "Census Tract"),
       list(agg_table = nowcast_agg_zip,
            agg_field = "ZCTA",
            sheet_name = "Zip Code"),
       list(agg_table = nowcast_agg_cty,
            agg_field = "County",
            sheet_name = "County"),
       list(agg_table = nowcast_agg_sd,
            agg_field = "school",
            sheet_name = "School Districts"))

if (exists("my_aux_geo")) {
  lAgg_for_output[[length(lAgg_for_output)+1]] <- 
    list(agg_table = nowcast_agg_aux,
         agg_field = "aux_geo_label",
         sheet_name = my_aux_geo_desc)
}

write_agg_output(outcomes_regex = outcomes_out_regex,
                 age_regex      = "age(_3$|_4$|_infant$|_toddler$)", # "_0to2|_3to5|_0to5|_6to12"
                 agg_levels     = lAgg_for_output,
                 out_label      = local_ccdf_name_short)

```


```{r optionally add other custom aggregations}

if (str_detect(my_output_tag, "^IL")) {
  # Adding reporting by an additional level of aggregation for just Illinois
  
  # See this website reference for how counties are grouped within payment regions:
  #   https://www.dhs.state.il.us/page.aspx?item=121213
  
  map_county_to_payreg <- function(cty) {
    case_when(str_detect(cty, "Cook|DeKalb|DuPage|Kane|Kendall|Lake|McHenry") ~ "Group 1A Counties",
              str_detect(cty, "Boone|Champaign|Kankakee|Madison|McLean|Monroe|Ogle|Peoria|Rock Island|Sangamon|St\\. Clair|Tazewell|Whiteside|^Will$|Winnebago|Woodford") ~ "Group 1B Counties",
              TRUE ~ "Group 2 Counties")
  }
  
  nowcast_elig_counts_final_aug <- 
    nowcast_elig_counts_final %>% 
    merge(geo_crosswalk[j = .(GEOID, County)] %>% unique(),
          by = "GEOID",
          all.x = TRUE) %>% 
    mutate(payment_reg = map_county_to_payreg(County))
  if (FALSE) {
    nowcast_elig_counts_final_aug %>% 
      dplyr::select(payment_reg, County) %>% 
      unique() %>% 
      arrange(payment_reg, County)
  }
  
  nowcast_agg_pay <- agg_tracts_up(nowcast_elig_counts_final_aug, "payment_reg") %>% arrange(payment_reg)
  
  for (ccdf_spec in str_subset(nowcast_elig_counts_final$outcome_vars, "ccdf_elig_incratio_")) {
    my_out_label <- 
      str_replace(ccdf_spec,
                  "ccdf_elig_incratio_(\\d+)",
                  "{local_ccdf_name_short} - \\1%")
    
    write_agg_output(x = nowcast_agg_pay %>% filter(outcome_var == ccdf_spec), 
                     agg_level = "payment_reg", 
                     sheet = "Payment Region", 
                     add = TRUE,
                     out_label = my_out_label)
  }
}
```

### Examine Final Estimates

#### Compare Estimates At Different Levels of Aggregation

```{r examine the dispersion of CCDF eligibility for potentially multiple income thresholds}

nowcast_agg_zip %>% 
  .[outcome_var %like% "ccdf_elig" & pd == "nowcast"] %>% 
  ggplot(aes(x = share,
             color = str_replace(outcome_var, ".+_(\\d+)$", "\\1%"))) +
  geom_density() +
  facet_wrap(~ age) +
  scale_x_continuous(labels = percent) +
  scale_color_discrete(name = "Income Eligibility Threshold") +
  labs(x = "% CCDF Eligibility") +
  theme_minimal() +
  theme(legend.position = "bottom")
```


```{r check that estimated eligibility is properly ordered across multiple ccdf income cutpoints, results = 'asis'}
if (exists("custom_income_thresh")) {
  
  cat("#### Compare Estimates Across CCDF Income Cutpoints\n\n")  
  
  plot_data <- 
    nowcast_agg_zip %>% 
    .[outcome_var %like% "ccdf_elig" & 
        pd == "nowcast" & 
        cps_base_recency == "most_recent" 
      ] %>% 
    .[j = `:=`(order = min(share),
               inc_thresh = 
                 outcome_var %>% 
                 str_replace(".+_(\\d+)$", "\\1%") %>% 
                 sort_by_char_nums()),
      by = .(ZCTA, age)]
  
  get_zcta_order <- function(z) plot_data[ZCTA == z, min(share)] 
  
  my_plot <- 
    ggplot(plot_data,
           aes(x = reorder(ZCTA, order),
               y = share,
               color = inc_thresh)) +
    geom_point(alpha = 0.2) + 
    geom_line() +
    facet_wrap(~ age) +
    scale_y_continuous(labels = percent) +
    scale_color_discrete(name = "Income Eligibility Threshold") +
    labs(x = "ZCTAs, in order of lowest income threshold") +
    theme(legend.position = "bottom",
          axis.text.x = element_blank())
  
  print(my_plot)
}
```


#### Map Levels and Differences

```{r generate static plots}
static_map_val <- function(estimates,
                           geo_level,
                           geo_level_merge_field = geo_level,
                           geo_level_desc = geo_level,
                           outcome,
                           field_desc,
                           plot_stat, # can take values "nowcast" or "diff"
                           map_title = NULL,
                           file_tag = "",
                           save_map = TRUE, 
                           val_limits = NULL,
                           show_legend = TRUE,
                           fill_trans  = "identity") { # an alternative is "sqrt"
  
  ### Prepare estimates -------------------------------------------------------#
  est_plot <- 
    estimates %>% 
    filter(outcome_var %like% outcome,
           cps_base_recency == case_match(plot_stat,
                                          "nowcast" ~ "most_recent",
                                          "diff"    ~ "allbase")) %>% 
    dplyr::select(-count, -count_se, -pop_count, -pop_count_se, -share_se, -cps_base_recency)
  
  est_wide <- 
    est_plot %>% 
    pivot_wider(names_from = pd,
                values_from = share) %>% 
    mutate(diff = nowcast - base,
           Age = 
             age %>% 
             str_replace_all(".+(\\d+)to(\\d+)", "Age \\1-\\2") %>% 
             str_replace_all("Age_(\\d+)", "Age \\1"))
  
  ### Join Geographic Data ----------------------------------------------------#
  myShp <- get(glue("{str_to_lower(geo_level)}Shp"))
  est_geo <- 
    est_wide %>% 
    merge(myShp,
          by = geo_level_merge_field) %>% 
    st_as_sf()
  
  ### Set plot options --------------------------------------------------------#
  # See this reference for setting `option` for scale_fill_viridis_c():
  #   https://ggplot2.tidyverse.org/reference/scale_viridis.html
  # See this as a visual reference for viridis color maps:
  #   https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html
  color_opt <- ifelse(plot_stat == "nowcast", 
                      "plasma",  # this is roughly yellow-red-purple
                      "viridis") # this is roughly yellow-green-purple
  
  if (plot_stat == "nowcast") {
    measure_label <- glue("Levels of {field_desc}")  
  } else {
    field_desc <- str_replace(field_desc, "\\(", glue("\\({base_year} - "))
    measure_label <- glue("Pct Pt Diff in {field_desc}")  
  }
  
  # Prep outcome description to work with filenaming
  measure_label_out <- 
    measure_label %>% 
    str_replace("<", "Below") %>% 
    str_replace("%", "pct")
  
  ### Generate Map Plot -------------------------------------------------------#
  my_plot <- 
    ggplot() +
    geom_sf(data = est_geo,
            aes_string(fill = plot_stat),
            linewidth = 0.025,
            color = "black")
  
  if (n_distinct(est_geo$Age) > 1) {
    my_plot <- 
      my_plot + 
      facet_wrap(~Age)
    title_age <- ""
  } else {
    title_age <- glue(", unique(est_geo$Age)")
  }
  
  # Finish map
  my_plot <-
    my_plot + 
    scale_fill_viridis_c(name = "",
                         limits = val_limits, 
                         option = color_opt,
                         trans = fill_trans,
                         labels = percent,
                         alpha = .4) +
    labs(title    = ifelse(!is.null(map_title), map_title, str_wrap(measure_label)),
         subtitle = ifelse( is.null(map_title),        "", str_wrap(measure_label))) +
    theme_void() 
  
  # Remove legend if not desired
  if (!show_legend) {
    my_plot <- 
      my_plot +
      theme(legend.position = "none")
  }
      
  if (save_map) {
    ggsave(plot = my_plot,
           filename = glue("{output_path}Map of {measure_label_out} for {geo_level_desc}{file_tag}_{my_output_tag}.png"),
           #width = 7,
           height = 7,
           units = "in")  
  }
  
  return(my_plot)
}
```


```{r map to generate maps for both levels and differences}
static_map_level_diff <- function(plot_stats = c("nowcast", "diff"),
                                  ...) {
  
  for (ps in plot_stats) {
    static_map_val(plot_stat = ps,
                   ...)
  }
}
```


```{r generate static plots of ccdf eligibility in levels and differences}

for (out_var in c("ccdf", "le100", "le200")) {
  out_var_desc <- 
    case_match(out_var,
               "ccdf"  ~ glue("{local_ccdf_name_short} Eligibility ({date_range})"),
               "le100" ~ glue("Head Start Eligibility ({date_range})"),
               "le200" ~ glue("Income <200% FPL ({date_range})"))
  
  static_map_level_diff(estimates = nowcast_agg_zip %>% filter(age == age_agg_main),
                        geo_level = "ZCTA",
                        outcome = out_var,
                        field_desc = out_var_desc,
                        save_map = TRUE, 
                        #val_limits = c(0, 0.6),
                        show_legend = TRUE)
  
  static_map_level_diff(estimates = nowcast_agg_cty %>% filter(age == age_agg_main),
                        geo_level = "County",
                        outcome = out_var,
                        field_desc = out_var_desc,
                        save_map = TRUE, 
                        #val_limits = c(0, 0.6),
                        show_legend = TRUE)
  
  static_map_level_diff(estimates = nowcast_agg_sd %>% filter(age == age_agg_main),
                        geo_level = "school",
                        outcome = out_var,
                        field_desc = out_var_desc,
                        save_map = TRUE, 
                        #val_limits = c(0, 0.6),
                        show_legend = TRUE)
  
  if (exists("my_aux_geo")) {
    static_map_level_diff(estimates = nowcast_agg_aux %>% filter(age == age_agg_main),
                          geo_level = "aux",
                          geo_level_merge_field = "aux_geo_label",
                          geo_level_desc = my_aux_geo_desc,
                          outcome = out_var,
                          field_desc = out_var_desc,
                          save_map = TRUE, 
                          #val_limits = c(0, 0.6),
                          show_legend = TRUE) 
  }
}
```


```{r generate tract-level maps within indicated geographies if specified for ccdf sensitivities}

if (exists("map_geos")) {
  lMap_out <- list(maps_by_geo = list(),
                   maps_by_inc = list())
  
  ccdf_outs <- 
    nowcast_agg_tract$outcome_var %>% 
    str_subset("ccdf") %>% 
    sort_by_char_nums() %>% 
    levels()
  
  map_geo_field <- 
    case_match(map_geo_level,
               "tract" ~ "GEOID",
               "county" ~ "County",
               "school" ~ "school")
  
  # Loop across ages
  for (a in age_agg_main) { 
    ests_a <- 
      nowcast_agg_tract %>% 
      filter(age == a,
             outcome_var %in% ccdf_outs)
    
    age_desc <- 
      a %>% 
      str_replace("age_(\\d+)to(\\d+)", "Age \\1-\\2") %>% 
      str_replace("age_(\\d+)", "Age \\1")
    
    share_range <- range(ests_a$share, na.rm = TRUE)
    
    # Loop across geographies
    
    for (g in map_geos) {
      
      # Identify tracts associated with the indicated geography
      if (str_to_lower(map_geo_level) == "county") {
        xwalk_g <- filter(geo_crosswalk, County == g)
      } else if (str_to_lower(map_geo_level) == "school") {
        xwalk_g <- filter(geo_crosswalk_sd, school == g)
      } else if (str_to_lower(map_geo_level) == "aux") {
        xwalk_g <- filter(geo_crosswalk_aux, get(my_aux_geo_field) == g)
      }
      
      map_tracts <- unique(xwalk_g$GEOID)
      ests_ag <- filter(ests_a, GEOID %in% map_tracts)
      
      for (o in ccdf_outs) {
        inc_thresh <- str_extract(o, "\\d+$")
        
        my_plot_ranged <- 
          static_map_val(estimates = ests_ag,
                         geo_level = "tract",
                         geo_level_merge_field = "GEOID",
                         outcome = o,
                         field_desc = 
                           glue("{local_ccdf_name_short} Eligibility - ",
                                "{inc_thresh}% {ccdf_income_thresh_label}, {age_desc} ",
                                "({date_range})"),
                         val_limits = share_range,
                         show_legend = TRUE,
                         map_title = g,
                         plot_stat = "nowcast",
                         file_tag = glue(" - {g}"),
                         save_map = FALSE)
        
        # lMap_out[["maps_by_inc"]] <- 
        #   append(lMap_out[["maps_by_inc"]],
        #          my_plot_ranged)
        lMap_out[["maps_by_inc"]][[length(lMap_out[["maps_by_inc"]]) + 1]] <- 
          my_plot_ranged
        
        # If it's the base CCDF income eligibility ratio, build a map with its own
        # scale to focus on geographic contrasts (rather than comparison of rates
        # across other income thresholds)
        if (str_detect(o, as.character(local_ccdf_incratio_base))) {
          my_plot_unranged <- 
            static_map_val(estimates = ests_ag,
                           geo_level = "tract",
                           geo_level_merge_field = "GEOID",
                           outcome = o,
                           field_desc = 
                             glue("{local_ccdf_name_short} Eligibility - ",
                                  "{inc_thresh}% {ccdf_income_thresh_label}, {age_desc} ",
                                  "({date_range})"),
                           val_limits = NULL,
                           show_legend = TRUE,
                           map_title = g,
                           plot_stat = "nowcast",
                           file_tag = glue(" - {g} - geographic contrast"),
                           save_map = FALSE)
          
          lMap_out[["maps_by_geo"]][[length(lMap_out[["maps_by_geo"]]) + 1]] <- 
            my_plot_unranged
        }
      }
    }
  } 
}
```


<!-- /!\ Could also consider generating a series of maps to show the logical progression of 
  ## ACS1 (PUMA)                    ... shows basic, baseline data
  -> ACS5 (tract w/PUMA overlay)    ... shows heterogeneity, as a predictor for SAE 
  -> SAE (tract with PUMA overlay)  ... shows SAE result
  -> Now-cast (tract)               ... shows changes
  -> geo aggregation                ... shows conversion to useful basis

-->

```{r if multiple ccdf cuts are specified -- contrast them statewide and at any geographic levels of focus}
if (length(local_ccdf_incratio_cuts) > 1 && exists("map_geos")) {
  lAggs <- 
    list(school = nowcast_agg_sd  %>% rename(geo = school),
         county = nowcast_agg_cty %>% rename(geo = County),
         zip    = nowcast_agg_zip %>% rename(geo = ZCTA))
  if (exists("my_aux_geo")) {
    lAggs[["aux"]] <- nowcast_agg_aux %>% rename(geo = aux_geo_label)
  }

  agg <- 
    lAggs[[map_geo_level]] %>% 
    filter(geo %in% map_geos,
           pd == "nowcast",
           cps_base_recency == "most_recent",
           outcome_var %like% "ccdf") %>% 
    select(geo, age, outcome_var, count, share) %>% 
    mutate(outcome_var = sort_by_char_nums(outcome_var)) %>% 
    arrange(age, geo, outcome_var) %>% 
    data.table() %>% 
    .[j = `:=`(added_count = count - lag(count),
               added_share = share - lag(share)),
      by = .(age, geo)] %>% 
    .[j = `:=`(added_count = ifelse(is.na(added_count), count, added_count),
               added_share = ifelse(is.na(added_share), share, added_share))]
    
  fig_comp_thresh_geos <- 
    agg %>% 
    filter(age == "age_0to5") %>% 
    mutate(outcome_var = factor(outcome_var, 
                                levels = rev(levels(outcome_var))),
           outcome_var = factor(outcome_var,
                                levels = levels(outcome_var),
                                labels = levels(outcome_var) %>% 
                                           str_extract("\\d+$") %>% 
                                           paste0("%")))%>% 
    ggplot(aes(x = factor(geo),
               y = added_share,
               fill = outcome_var)) +
    geom_bar(stat = "identity",
             width = 0.3) +
    scale_y_continuous(labels = percent) +
    scale_fill_viridis_d(name = glue("Income Threshold\nas % of {ccdf_income_thresh_label}"),
                         option = "G",
                         guide = guide_legend(reverse = TRUE,
                                              byrow = TRUE)) +
    labs(title = glue("Increases in Estimated {local_ccdf_name_short} Eligibility for Increasing the Income Threshold"),
         subtitle = "by Selected Geographies",
         x = "",
         y = glue("{local_ccdf_name_short} Eligibility")) +
    theme_minimal() +
    theme(axis.text = element_text(size = 12),
          legend.position = "bottom",
          legend.title = element_text(hjust = 1),
          axis.text.x = element_text(angle = 90))
}
```


```{r collect output into presentation deck}
# This powerpoint output is intended to capture the figures and maps generated
# below for easy display
if (exists("map_geos")) {
  ppt <- 
    read_pptx() %>% 
    add_slide(layout = "Title Slide") %>% 
    ph_with(glue("Maps and Figures for Examining {local_ccdf_name_short} Eligibility for {my_state_abbr}"),
            location = ph_location_type(type = "ctrTitle"))
  
  if (exists("map_geos")) {
    # Generate slides for geographic contrasts
    ppt <- 
      ppt %>% 
      add_slide(layout = "Section Header") %>% 
      ph_with(glue("Maps Showing {local_ccdf_name_short} Eligibility by Select Geographies"),
              location = ph_location_type(type = "title"))
    
    for (i in 1:length(lMap_out$maps_by_geo)) {
      ppt <- 
        ppt %>% 
        add_slide() %>% 
        ph_with(lMap_out$maps_by_geo[[i]],
                location = ph_location_type(type = "body"))
    }  
    
    # If multiple threshold cutpoints had been selected, output those figures
    if (length(local_ccdf_incratio_cuts) > 1) {
      ppt <- 
        ppt %>% 
        add_slide(layout = "Section Header") %>% 
        ph_with(glue("Increase of Eligibility by Hypothetical Income Thresholds"),
                location = ph_location_type(type = "title")) %>% 
        add_slide() %>% 
        ph_with(fig_comp_thresh_geos,
                location = ph_location_type(type = "body")) %>% 
        add_slide(layout = "Section Header") %>% 
        ph_with(glue("Maps Showing {local_ccdf_name_short} Eligibility by Income Threshold for Select Geographies"),
                location = ph_location_type(type = "title"))
      
      for (i in 1:length(lMap_out$maps_by_inc))
        ppt <- 
          ppt %>% 
          add_slide() %>% 
          ph_with(lMap_out$maps_by_inc[[i]],
                  location = ph_location_type(type = "body"))
    }
    
    # Output
    print(ppt, 
          target = glue("{output_path}Maps and Figures for Examining {local_ccdf_name_short} Eligibility for {my_state_abbr} - {my_output_tag}.pptx"))
  } 
}
```

